### ISSUE TITLE
df_console.py: error: unrecognized arguments: --online

### ISSUE THREAD

**Issue by alatyshe** [facebookresearch/ELF#113]
Run console_df_mcts.sh - get:
```
sh console_df_mcts.sh
usage: df_console.py [-h] [--actor_only] [--list_file LIST_FILE] [--verbose]
                     [--data_aug DATA_AUG] [--ratio_pre_moves RATIO_PRE_MOVES]
                     [--start_ratio_pre_moves START_RATIO_PRE_MOVES]
                     [--num_games_per_thread NUM_GAMES_PER_THREAD]
                     [--move_cutoff MOVE_CUTOFF] [--mode MODE] [--use_mcts]
                     [--gpu GPU] [--num_games NUM_GAMES]
                     [--batchsize BATCHSIZE] [--game_multi GAME_MULTI] [--T T]
                     [--eval] [--wait_per_group]
                     [--num_collectors NUM_COLLECTORS] [--verbose_comm]
                     [--verbose_collector] [--mcts_threads MCTS_THREADS]
                     [--mcts_rollout_per_thread MCTS_ROLLOUT_PER_THREAD]
                     [--mcts_verbose]
                     [--mcts_save_tree_filename MCTS_SAVE_TREE_FILENAME]
                     [--mcts_verbose_time] [--mcts_use_prior]
                     [--mcts_pseudo_games MCTS_PSEUDO_GAMES]
                     [--mcts_pick_method MCTS_PICK_METHOD]
                     [--additional_labels ADDITIONAL_LABELS]
                     [--multipred_no_backprop]
                     [--sample_policy {epsilon-greedy,multinomial,uniform}]
                     [--greedy] [--epsilon EPSILON]
                     [--sample_nodes SAMPLE_NODES] [--load LOAD]
                     [--onload ONLOAD] [--omit_keys OMIT_KEYS] [--no_bn]
                     [--no_leaky_relu] [--num_layer NUM_LAYER] [--dim DIM]
                     [--opt_method OPT_METHOD] [--lr LR] [--adam_eps ADAM_EPS]
                     [--keys_in_reply KEYS_IN_REPLY]
df_console.py: error: unrecognized arguments: --online
```

**Comment by alatyshe** [comment]
after edit file and run it i get another error:
```
PID: 19192
========== Args ============
Loader: actor_only=False,list_file="./train.lst",verbose=False,data_aug=-1,ratio_pre_moves=0,start_ratio_pre_moves=0.5,num_games_per_thread=1,move_cutoff=-1,mode="online",use_mcts=True,gpu=None
ContextArgs: num_games=1,batchsize=1,game_multi=None,T=1,eval=False,wait_per_group=False,num_collectors=0,verbose_comm=False,verbose_collector=False,mcts_threads=0,mcts_rollout_per_thread=1,mcts_verbose=False,mcts_save_tree_filename="",mcts_verbose_time=False,mcts_use_prior=False,mcts_pseudo_games=0,mcts_pick_method="most_visited"
MoreLabels: additional_labels="aug_code,move_idx"
MultiplePrediction: multipred_no_backprop=False
Sampler: sample_policy="epsilon-greedy",greedy=True,epsilon=0.0,sample_nodes="pi,a"
ModelLoader: load=None,onload=None,omit_keys=None,no_bn=False,no_leaky_relu=False,num_layer=39,dim=128
ModelInterface: opt_method="adam",lr=0.001,adam_eps=0.001
Evaluator: keys_in_reply=""
========== End of Args ============
Warning: key = num_minibatch cannot be found from either args or environment!
#Game: 1
#Max_thread: 0
#Collectors: 0
T: 1
Wait per group: False
Maximal #moves (0 = no constraint): 0
#Threads: 0
#Rollout per thread: 1
Verbose: False, Verbose_time: False
Use prior: False
Persistent tree: False
#Pseudo game: 0
Pick method: most_visited

Loading ./train.lst failed!
Version:  6a769a02dc0ab11e5a7633c337b5d3ce0d0bf511_staged
Num Actions:  361
#recv_thread = 1
Group 0:
  Collector[0] Batchsize: 1 Info: [gid=0][T=1][name="human_actor"]
Group 1:
  Collector[1] Batchsize: 1 Info: [gid=1][T=1][name="actor"]

KEY HERE :  actor
self IDX:  defaultdict(<class 'list'>, {'human_actor': [0], 'actor': [1]})
cb :  <function DFConsole.main_loop.<locals>.actor at 0x7f52745ff0d0>
KEY HERE :  human_actor
self IDX:  defaultdict(<class 'list'>, {'human_actor': [0], 'actor': [1]})
cb :  <function DFConsole.main_loop.<locals>.human_actor at 0x7f52745ff158>
In human_actor
Traceback (most recent call last):
  File "df_console.py", line 219, in <module>
    console.main_loop()
  File "df_console.py", line 213, in main_loop
    GC.Run()
  File "/home/ubuntu/arvi_dima/ELF/elf/utils_elf.py", line 381, in Run
    res = self._call(self.infos)
  File "/home/ubuntu/arvi_dima/ELF/elf/utils_elf.py", line 362, in _call
    reply = self._cb[infos.gid](picked)
  File "df_console.py", line 194, in human_actor
    return self.prompt("DF> ", batch)
  File "df_console.py", line 97, in prompt
    print(batch.GC.ShowBoard(0))
AttributeError: 'Batch' object has no attribute 'GC'
Prepare to stop ...
```
