### ISSUE TITLE
KeyError: 'Batch(): specified key: res or last_res not found!'

### ISSUE THREAD

**Issue by HFly1** [facebookresearch/ELF#131]
0%|                    | 0/5000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 40, in <module>
    runner.run()
  File "/home/fly/Documents/ELF-master/rlpytorch/runner/single_process.py", line 56, in run
    self.GC.Run()
  File "/home/fly/Documents/ELF-master/elf/utils_elf.py", line 381, in Run
    res = self._call(self.infos)
  File "/home/fly/Documents/ELF-master/elf/utils_elf.py", line 362, in _call
    reply = self._cb[infos.gid](picked)
  File "/home/fly/Documents/ELF-master/rlpytorch/trainer/trainer.py", line 154, in actor
    return self.evaluator.actor(batch)
  File "/home/fly/Documents/ELF-master/rlpytorch/trainer/trainer.py", line 73, in actor
    state_curr = m.forward(batch.hist(0))
  File "./rts/game_MC/model_unit_cmd.py", line 55, in forward
    s, res = x["s"], x["res"]
  File "/home/fly/Documents/ELF-master/elf/utils_elf.py", line 114, in __getitem__
    raise KeyError("Batch(): specified key: %s or %s not found!" % (key, key_with_last))
KeyError: 'Batch(): specified key: res or last_res not found!'

**Comment by HFly1** [comment]
fly@fly-System-Product-Name:~/Documents/ELF-master$ sh ./train_minirts_unitcmd.sh --gpu 0

**Comment by HFly1** [comment]
How do i do?
