### ISSUE TITLE
Error when using GPU

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#31]
If I set --gpu 0 to run run.py, everything is fine.
But if I choose other gpu to use, for example --gpu 1, I will get the error as follow:

chenyukang@node02:~/ELF$ game=./rts/game_MC/game model=actor_critic model_file=./rts/game_MC/model python3 run.py --batchsize 128 --freq_update 50 --fs_opponent 20 --latest_start 500 --latest_start_decay 0.99 --num_games 1024 --opponent_type AI_HIT_AND_RUN --tqdm --num_episode 1000 --gpu 7 --save_dir ./save
Namespace(T=6, actor_only=False, additional_labels=None, ai_type='AI_NN', batchsize=128, discount=0.99, entropy_ratio=0.01, epsilon=0.0, eval=False, freq_update=50, fs_ai=50, fs_opponent=20, game_multi=None, gpu=7, grad_clip_norm=None, greedy=False, handicap_level=0, latest_start=500, latest_start_decay=0.99, load=None, max_tick=30000, mcts_threads=64, min_prob=1e-06, num_episode=1000, num_games=1024, num_minibatch=5000, opponent_type='AI_HIT_AND_RUN', ratio_change=0, record_dir='./record', sample_node='pi', sample_policy='epsilon-greedy', save_dir='./save', save_prefix='save', seed=0, simple_ratio=-1, tqdm=True, verbose_collector=False, verbose_comm=False, wait_per_group=False)
Version:  cc84f9b70e52759a90ffe5a92278e8d54ba6b136_staged
Num Actions:  9
Num unittype:  6
  0%|                                                                                                      | 0/5000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "run.py", line 205, in <module>
    runner.run()
  File "/home/chenyukang/ELF/rlpytorch/trainer.py", line 208, in run
    self.GC.Run()
  File "/home/chenyukang/ELF/elf/utils_elf.py", line 224, in Run
    res = self._call(self.infos)
  File "/home/chenyukang/ELF/elf/utils_elf.py", line 211, in _call
    reply = self._cb[infos.gid](sel, sel_gpu)
  File "/home/chenyukang/ELF/rlpytorch/trainer.py", line 139, in actor
    state_curr = self.mi.forward("actor", sel_gpu[0])
  File "/home/chenyukang/ELF/rlpytorch/model_interface.py", line 102, in forward
    _, res = self.models[key](x)
  File "/home/chenyukang/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "./rts/game_MC/model.py", line 79, in forward
    output = self.net(self._var(s), self._var(r0), self._var(r1))
  File "/home/chenyukang/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "./rts/game_MC/model.py", line 42, in forward
    h1 = self.conv1(input.view(input.size(0), self.m, 20, 20))
  File "/home/chenyukang/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenyukang/anaconda3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/chenyukang/anaconda3/lib/python3.5/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: tensors are on different GPUs

It seems that the parameter 'all_args.gpu' is not given to inner model.

**Comment by qucheng** [comment]
I cannot reproduce it.
A possible work around is to specify CUDA_VISIBLE_DEVICES=1 and you can still use --gpu 0

**Comment by yukang2017** [comment]
Thank you.
