### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by xiahouzuoxin** [facebookresearch/ELF#39]
```
root@b6252d26dc95:/workspace# game=./rts/game_MC/game model=actor_critic model_file=./rts/game_MC/model taskset -c 0-9 python3 run.py --batchsize 128 --freq_update 50 --fs_opponent 20 --latest_start 500 --latest_start_decay 0.99 --num_games 1024 --opponent_type AI_SIMPLE --tqdm
Traceback (most recent call last):
  File "run.py", line 142, in <module>
    game = load_module(os.environ["game"]).Loader()
  File "/workspace/rlpytorch/utils.py", line 510, in load_module
    module = __import__(os.path.basename(mod))
  File "./rts/game_MC/game.py", line 8, in <module>
    import minirts
ImportError: dynamic module does not define module export function (PyInit_minirts)
```

I compiled game_MC success

**Comment by xiahouzuoxin** [comment]
I solved this, because of the Makefile under `rts/game_MC/Makefile` use python2 to generate .so. I change those lines as follows.
```
PYTHON ?= python3
PYTHON_CONFIG ?= python3-config
```

Import error disappeared, but an new `Segmentation fault` error occur,

```
root@b6252d26dc95:/workspace# game=./rts/game_MC/game model=actor_critic model_file=./rts/game_MC/model taskset -c 0-9 python3 run.py --batchsize 128 --freq_update 50 --fs_opponent 20 --latest_start 500 --latest_start_decay 0.99 --num_games 1024 --opponent_type AI_SIMPLE --tqdm
Namespace(T=6, actor_only=False, additional_labels=None, ai_type='AI_NN', batchsize=128, discount=0.99, entropy_ratio=0.01, epsilon=0.0, eval=False, freq_update=50, fs_ai=50, fs_opponent=20, game_multi=None, gpu=None, grad_clip_norm=None, greedy=False, handicap_level=0, latest_start=500, latest_start_decay=0.99, load=None, max_tick=30000, mcts_threads=64, min_prob=1e-06, num_episode=10000, num_games=1024, num_minibatch=5000, opponent_type='AI_SIMPLE', ratio_change=0, record_dir='./record', sample_node='pi', sample_policy='epsilon-greedy', save_dir=None, save_prefix='save', seed=0, simple_ratio=-1, tqdm=True, verbose_collector=False, verbose_comm=False, wait_per_group=False)
Segmentation fault (core dumped)
```

**Comment by yuandong-tian** [comment]
What is your gcc version and OS?

**Comment by qucheng** [comment]
Can you try the solution in issue #27

**Comment by yuandong-tian** [comment]
f268feb9fae77584521208414af06a3ee6728d40 might address your issue.
